language: android
dist: trusty
jdk: oraclejdk8
install: true
script:
  - scripts/travis.sh

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - sys-img-armeabi-v7a-android-30
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"